apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-openshift-virtualization
  namespace: openshift-cnv
rules:
- apiGroups:
  - hco.kubevirt.io
  resources:
  - hyperconvergeds
  verbs:
  - create
  - update
  - patch
  - delete
- apiGroups:
  - cdi.kubevirt.io
  resources:
  - datavolumes
  verbs:
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ogaac-openshift-virtualization
  namespace: openshift-cnv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-openshift-virtualization
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
