apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: centosvm
      vm.kubevirt.io/template: centos8-server-small
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.14.0
    name: centosvm
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: centosvm
      spec:
        pvc:
          accessModes:
          - ReadWriteMany
          resources:
            requests:
              storage: 30Gi
        source:
          pvc:
            name: centos8
            namespace: openshift-virtualization-os-images
    running: false
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: small
          vm.kubevirt.io/os: centos8
          vm.kubevirt.io/workload: server
        labels:
          kubevirt.io/domain: centosvm
          kubevirt.io/size: small
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: centosvm
            - disk:
                bus: virtio
              name: cloudinitdisk
            interfaces:
            - masquerade: {}
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 2Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: centosvm
          name: centosvm
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: centos
              password: 30jt-pghb-jj0i
              chpasswd: { expire: False }
          name: cloudinitdisk
kind: List
metadata: {}
