apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-windows
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/overlays/windows
    repoURL: https://github.com/cwilkers/kubevirt-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
